add dry_run mode

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -18,6 +18,10 @@ inputs:
     description: The version of Python to use.
     required: false
     default: "3.9"
+  dry_run:
+    description: Whether to run the deployment in dry-run mode.
+    required: false
+    default: "false"
 runs:
   using: "composite"
   steps:
@@ -27,9 +31,14 @@ runs:
       uses: actions/setup-python@v5
       with:
         python-version: ${{ inputs.python_version }}
-    - name: Install Reflex CLI
+    - name: Install Reflex & Dependencies
       run: |
-        pip install -r ${{ inputs.app_directory }}/requirements.txt
+        REQUIREMENTS_FILE="${{ inputs.app_directory }}/requirements.txt"
+        if ! grep -q "^reflex" "$REQUIREMENTS_FILE"; then
+          echo "Error: 'reflex' is not listed in $REQUIREMENTS_FILE."
+          exit 1
+        fi
+        pip install -r "$REQUIREMENTS_FILE"
       shell: bash
     - name: Deploy Reflex App
       run: |
